import type { MaterialDefinition } from "../../types/material";

export const flexMaterial: MaterialDefinition = {
  name: "Flex",
  displayName: "Flex",
  description: "A flexbox container for laying out children in a row or column with alignment control.",
  category: "layout",
  icon: "AlignJustify",
  defaultProps: {
    direction: "row",
    justify: "start",
    align: "start",
    wrap: false,
    gap: "4",
  },
  supportsChildren: true,
  isContainer: true,
  editableProps: [
    {
      key: "direction",
      label: "Direction",
      type: "select",
      defaultValue: "row",
      options: [
        { label: "Row", value: "row" },
        { label: "Column", value: "column" },
      ],
      group: "Layout",
      order: 1,
    },
    {
      key: "justify",
      label: "Justify Content",
      type: "select",
      defaultValue: "start",
      options: [
        { label: "Start", value: "start" },
        { label: "Center", value: "center" },
        { label: "End", value: "end" },
        { label: "Between", value: "between" },
      ],
      group: "Layout",
      order: 2,
    },
    {
      key: "align",
      label: "Align Items",
      type: "select",
      defaultValue: "start",
      options: [
        { label: "Start", value: "start" },
        { label: "Center", value: "center" },
        { label: "End", value: "end" },
        { label: "Stretch", value: "stretch" },
      ],
      group: "Layout",
      order: 3,
    },
    {
      key: "wrap",
      label: "Wrap",
      type: "switch",
      defaultValue: false,
      group: "Layout",
      order: 4,
    },
    {
      key: "gap",
      label: "Gap",
      type: "text",
      defaultValue: "4",
      group: "Layout",
      order: 5,
    },
    {
      key: "className",
      label: "Tailwind Classes",
      type: "tailwind",
      group: "Styling",
      order: 10,
    },
  ],
};
