import type { MaterialDefinition } from "../../types/material";

export const gridMaterial: MaterialDefinition = {
  name: "Grid",
  displayName: "Grid",
  description: "A CSS Grid container with configurable columns. Great for responsive layouts.",
  category: "layout",
  icon: "Grid3x3",
  defaultProps: {
    columns: 3,
    gap: "4",
  },
  supportsChildren: true,
  isContainer: true,
  editableProps: [
    {
      key: "columns",
      label: "Columns",
      type: "number",
      defaultValue: 3,
      min: 1,
      max: 12,
      group: "Layout",
      order: 1,
    },
    {
      key: "rows",
      label: "Rows",
      type: "number",
      defaultValue: 0,
      min: 0,
      max: 12,
      group: "Layout",
      order: 2,
    },
    {
      key: "autoFlow",
      label: "Auto Flow",
      type: "select",
      defaultValue: "row",
      options: [
        { label: "Row", value: "row" },
        { label: "Column", value: "column" },
        { label: "Dense", value: "dense" },
        { label: "Row Dense", value: "row dense" },
        { label: "Column Dense", value: "column dense" },
      ],
      group: "Layout",
      order: 3,
    },
    {
      key: "justifyItems",
      label: "Justify Items",
      type: "select",
      defaultValue: "stretch",
      options: [
        { label: "Start", value: "start" },
        { label: "Center", value: "center" },
        { label: "End", value: "end" },
        { label: "Stretch", value: "stretch" },
      ],
      group: "Layout",
      order: 4,
    },
    {
      key: "alignItems",
      label: "Align Items",
      type: "select",
      defaultValue: "stretch",
      options: [
        { label: "Start", value: "start" },
        { label: "Center", value: "center" },
        { label: "End", value: "end" },
        { label: "Stretch", value: "stretch" },
      ],
      group: "Layout",
      order: 5,
    },
    {
      key: "gap",
      label: "Gap",
      type: "number",
      defaultValue: 4,
      min: 0,
      max: 12,
      group: "Layout",
      order: 6,
    },
    {
      key: "className",
      label: "Tailwind Classes",
      type: "tailwind",
      group: "Styling",
      order: 10,
    },
  ],
};
