/**
 * YAML ↔ JSON 双向转换器
 *
 * 实现流程定义的 YAML 格式与 JSON 格式之间的双向转换。
 * 依赖 eemeli/yaml 库进行 YAML 解析和序列化。
 * 转换操作：
 * - YAML → JSON: 解析 YAML 字符串为 FlowDefinition 对象
 * - JSON → YAML: 将 FlowDefinition 对象序列化为格式化的 YAML 字符串
 *
 * YAML 格式示例见 Thing Model 规范文档。
 *
 * @author xiye
 * @date 2026-06-14
 */

import YAML from "yaml";
import type { FlowDefinition, ConversionResult } from "../thing-model/types";
import { flowDefinitionSchema } from "../thing-model/schema";

/**
 * YAML 字符串 → FlowDefinition JSON 对象
 *
 * 解析 YAML 格式的流程定义字符串为结构化的 FlowDefinition 对象，
 * 并执行 Zod schema 验证确保数据完整性。
 *
 * @param yamlString - YAML 格式的流程定义字符串
 * @returns 转换结果，包含解析后的 FlowDefinition 或错误信息
 */
export function yamlToJson(yamlString: string): ConversionResult {
  try {
    if (!yamlString || yamlString.trim().length === 0) {
      return { success: false, error: "YAML 内容为空" };
    }

    const parsed = YAML.parse(yamlString);

    if (!parsed || typeof parsed !== "object") {
      return { success: false, error: "YAML 解析结果不是有效的对象" };
    }

    const validationResult = flowDefinitionSchema.safeParse(parsed);

    if (!validationResult.success) {
      const messages = validationResult.error.issues
        .map((issue) => `  - ${issue.path.join(".")}: ${issue.message}`)
        .join("\n");

      return {
        success: false,
        error: `YAML 内容格式不符合 Thing Model 规范:\n${messages}`,
      };
    }

    return { success: true, data: validationResult.data };
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    return { success: false, error: `YAML 解析失败: ${message}` };
  }
}

/**
 * FlowDefinition JSON 对象 → YAML 字符串
 *
 * 将流程定义对象序列化为可读的 YAML 格式字符串，
 * 用于文件导出和版本控制。
 *
 * @param flowDefinition - 流程定义对象
 * @returns 转换结果，包含 YAML 字符串或错误信息
 */
export function jsonToYaml(flowDefinition: FlowDefinition): ConversionResult {
  try {
    const doc = new YAML.Document(flowDefinition, { schema: "core" });

    const yamlString = doc.toString({
      indent: 2,
      lineWidth: 0, // 不自动换行
    });

    return { success: true, data: yamlString };
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    return { success: false, error: `JSON 转 YAML 失败: ${message}` };
  }
}

/**
 * 流程定义对象 → YAML 文件内容（带文件头注释）
 *
 * 生成包含版权说明和文档链接的 YAML 文件内容，
 * 适用于导出到项目仓库的 .flow.yaml 文件。
 *
 * @param flowDefinition - 流程定义对象
 * @returns YAML 文件内容字符串
 */
export function jsonToYamlFile(flowDefinition: FlowDefinition): string {
  const header = [
    `# Thing Model Flow Definition`,
    `# Generated by Envelope V3`,
    `#`,
    `# Thing: ${flowDefinition.thing}`,
    `# Version: ${flowDefinition.version}`,
    ...(flowDefinition.description ? [`# Description: ${flowDefinition.description}`] : []),
    `#`,
    `# 此文件遵循 Thing Model 规范，可被 Envelope 编辑器导入。`,
    `# 修改节点列表和连线即可改变流程行为。`,
    `#`,
    ``,
  ].join("\n");

  const result = jsonToYaml(flowDefinition);

  if (!result.success || typeof result.data !== "string") {
    return header + "# Error: YAML 序列化失败";
  }

  return header + result.data;
}

/**
 * 验证流程定义的 YAML 往返转换一致性
 *
 * 将 FlowDefinition 转为 YAML 再解析回来，
 * 检查是否丢失数据（往返保真度测试）。
 *
 * @param flowDefinition - 原始流程定义
 * @returns 如果往返后一致返回 true
 */
export function validateRoundTrip(flowDefinition: FlowDefinition): boolean {
  const yamlResult = jsonToYaml(flowDefinition);

  if (!yamlResult.success || typeof yamlResult.data !== "string") {
    return false;
  }

  const jsonResult = yamlToJson(yamlResult.data);

  if (!jsonResult.success || !jsonResult.data || typeof jsonResult.data === "string") {
    return false;
  }

  const reParsed = jsonResult.data;

  // Deep comparison: use JSON.stringify for structural equality check.
  const originalNormalized = JSON.stringify(normalizeFlowDef(flowDefinition));
  const reParsedNormalized = JSON.stringify(normalizeFlowDef(reParsed));

  return originalNormalized === reParsedNormalized;
}

/** 标准化 FlowDefinition 用于深度对比（按 ID 排序以确保顺序无关） */
function normalizeFlowDef(def: FlowDefinition): FlowDefinition {
  return {
    thing: def.thing,
    version: def.version,
    description: def.description,
    nodes: [...def.nodes].sort((a, b) => a.id.localeCompare(b.id)),
    edges: [...def.edges].sort((a, b) => a.id.localeCompare(b.id)),
  };
}
