import React from 'react';
import SDropdown from '@/materials/absolute-semantic/control/Dropdown';

const attr = {
  header: 'Select Header',
  icon: 'home',
  text: 'Select',
  basic: true,
  selection: true,
  compact: false,
  deburr: false,
  defaultOpen: false,
  direction: 'right',
  disabled: false,
  error: false,
  floating: false,
  fluid: true,
  inline: true,
  item: true,
  labeled: true,
  lazyLoad: true,
  dataSource: [
    {
      id: '1',
      key: 'Jenny Hess',
      text: 'Jenny Hess',
      value: 'Jenny Hess',
      flag: '',
      icon: '',
      image: '',
      description: 'ctrl + o',
    },
    {
      id: '2',
      key: 'Elliot Fu',
      text: 'Elliot Fu',
      value: 'Elliot Fu',
      flag: 'cn',
      icon: 'home',
      image: '',
      description: 'ctrl + c',
    },
    {
      id: '3',
      key: 'Stevie Feliciano',
      text: 'Stevie Feliciano',
      value: 'Stevie Feliciano',
      flag: '',
      icon: 'home',
      image: 'https://s1.ax1x.com/2023/03/27/ppsbWan.jpg',
      description: 'ctrl + c',
    },
    {
      id: '4',
      key: 'Matt',
      text: 'Matt',
      value: 'Matt',
      flag: '',
      icon: 'dropdown',
      image: '',
      description: '',
    },
    {
      id: '5',
      key: 'Justen Kitsune',
      text: 'Justen Kitsune',
      value: 'Justen Kitsune',
      flag: 'af',
      icon: '',
      image: '',
      description: 'Hello',
    },
    {
      id: '6',
      key: 'Xiye',
      text: 'Xiye',
      value: 'Xiye',
      flag: '',
      icon: '',
      image: '',
      description: 'Hello',
    },
    {
      id: '7',
      key: 'Cayon',
      text: 'Cayon',
      value: 'Cayon',
      flag: '',
      icon: 'home',
      image: '',
      description: '',
    },
  ],
};

export default () => (
  /*@ts-ignore*/
  <SDropdown isTpl={false} {...attr} />
);
