import type { MaterialDefinition } from "../../types/material";

export const radioGroupMaterial: MaterialDefinition = {
  name: "RadioGroup",
  displayName: "Radio Group",
  description: "A set of checkable buttons where only one can be selected.",
  category: "form",
  icon: "Circle",
  supportsChildren: true,
  defaultProps: {
    options: ["Option 1", "Option 2"],
  },
  bindableEvents: ["onChange"],
  editableProps: [
    {
      key: "name",
      label: "Field Name",
      type: "text",
      defaultValue: "",
      group: "Behavior",
      order: 0,
      comment: "字段标识，表单提交时的 key",
    },
    {
      key: "defaultValue",
      label: "Default Value",
      type: "text",
      defaultValue: "",
      group: "Behavior",
      order: 1,
    },
    {
      key: "orientation",
      label: "Orientation",
      type: "select",
      options: [
        { label: "Vertical", value: "vertical" },
        { label: "Horizontal", value: "horizontal" },
      ],
      defaultValue: "vertical",
      group: "Appearance",
      order: 2,
    },
    {
      key: "disabled",
      label: "Disabled",
      type: "switch",
      defaultValue: false,
      group: "State",
      order: 3,
    },
    {
      key: "required",
      label: "Required",
      type: "switch",
      defaultValue: false,
      group: "Validation",
      order: 4,
    },
    {
      key: "options",
      label: "Options",
      type: "json",
      defaultValue: ["Option 1", "Option 2"],
      group: "Slots",
      order: 5,
    },
    {
      key: "className",
      label: "Tailwind Classes",
      type: "tailwind",
      group: "Styling",
      order: 10,
    },
    {
      key: "comment",
      label: "Comment",
      type: "textarea",
      group: "Documentation",
      order: 20,
    },
  ],
};

export const radioGroupItemMaterial: MaterialDefinition = {
  name: "RadioGroupItem",
  displayName: "Radio Item",
  description: "An individual radio button within a Radio Group.",
  category: "form",
  icon: "CircleDot",
  supportsChildren: true,
  editableProps: [
    {
      key: "value",
      label: "Value",
      type: "text",
      defaultValue: "",
      required: true,
      group: "Behavior",
      order: 1,
    },
    {
      key: "label",
      label: "Label",
      type: "text",
      defaultValue: "Option",
      group: "Content",
      order: 2,
    },
    {
      key: "disabled",
      label: "Disabled",
      type: "switch",
      defaultValue: false,
      group: "State",
      order: 3,
    },
    {
      key: "className",
      label: "Tailwind Classes",
      type: "tailwind",
      group: "Styling",
      order: 10,
    },
  ],
};
