import type { MaterialDefinition } from "../../types/material";

export const switchMaterial: MaterialDefinition = {
  name: "Switch",
  displayName: "Switch",
  description: "A control that toggles between checked and unchecked states.",
  category: "form",
  icon: "ToggleLeft",
  bindableEvents: ["onChange"],
  editableProps: [
    {
      key: "name",
      label: "Field Name",
      type: "text",
      defaultValue: "",
      group: "Behavior",
      order: 0,
      comment: "字段标识，表单提交时的 key",
    },
    {
      key: "label",
      label: "Label",
      type: "text",
      defaultValue: "",
      group: "Content",
      order: 1,
    },
    {
      key: "defaultChecked",
      label: "Checked by Default",
      type: "switch",
      defaultValue: false,
      group: "State",
      order: 2,
    },
    {
      key: "disabled",
      label: "Disabled",
      type: "switch",
      defaultValue: false,
      group: "State",
      order: 3,
    },
    {
      key: "required",
      label: "Required",
      type: "switch",
      defaultValue: false,
      group: "Validation",
      order: 4,
    },
    {
      key: "className",
      label: "Tailwind Classes",
      type: "tailwind",
      group: "Styling",
      order: 10,
    },
    {
      key: "comment",
      label: "Comment",
      type: "textarea",
      group: "Documentation",
      order: 20,
    },
  ],
};
