import type { MaterialDefinition } from "../../types/material";

export const textareaMaterial: MaterialDefinition = {
  name: "Textarea",
  displayName: "Textarea",
  description: "A multi-line text input for longer form content.",
  category: "form",
  icon: "Text",
  editableProps: [
    {
      key: "name",
      label: "Field Name",
      type: "text",
      defaultValue: "",
      group: "Behavior",
      order: 0,
      comment: "字段标识，表单提交时的 key",
    },
    {
      key: "placeholder",
      label: "Placeholder",
      type: "text",
      defaultValue: "",
      group: "Content",
      order: 1,
    },
    {
      key: "rows",
      label: "Rows",
      type: "number",
      defaultValue: 3,
      min: 1,
      max: 20,
      group: "Appearance",
      order: 2,
    },
    {
      key: "disabled",
      label: "Disabled",
      type: "switch",
      defaultValue: false,
      group: "State",
      order: 3,
    },
    {
      key: "required",
      label: "Required",
      type: "switch",
      defaultValue: false,
      group: "Validation",
      order: 4,
    },
    {
      key: "pattern",
      label: "Pattern",
      type: "text",
      placeholder: "e.g. [a-zA-Z]+",
      group: "Validation",
      order: 5,
    },
    {
      key: "minLength",
      label: "Min Length",
      type: "number",
      min: 0,
      group: "Validation",
      order: 6,
    },
    {
      key: "maxLength",
      label: "Max Length",
      type: "number",
      min: 0,
      group: "Validation",
      order: 7,
    },
    {
      key: "className",
      label: "Tailwind Classes",
      type: "tailwind",
      group: "Styling",
      order: 10,
    },
    {
      key: "comment",
      label: "Comment",
      type: "textarea",
      group: "Documentation",
      order: 20,
    },
  ],
};
